### PR TITLE
Building with Backgrounds and Gradients

### PR DESCRIPTION
**Pull request by adamclasic**
This project consists of building a webpage using images as a background and adding gradients to elements. The goal is to make a clone of old an old version of the Apple website webpage.

### CODE REVIEW

**Comment by kobiyoyo** [comment]
## Pull Request under review, by Adama Chubiyojo Desmond (TSE)

**Review by kobiyoyo — CHANGES_REQUESTED** [review]
## Hi @adamclasic      
#### Great Job so far, but there are a few more things required. 
#### General
- [ ] Please next project Your Branch name should have a meaningful title.
- [ ] Comments: It’s better to delete the commented code. If you need to review a previous version of your code, use git history ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/general/no_inline_comments.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/66243643/))
### Page structure

#### Navbar
 - [ ] The navbar should have a search field on the rightmost section
#### Original Version


#### Your Version


### Make changes and submit another code review request.
*Happy coding*

**Comment by adamclasic** [comment]
@kobiyoyo Thank you I will start with the required changes.
I have been getting this " Please next project Your Branch name should have a meaningful title." since the start of Microverse.
Can you please give me an example or instructions?

**Review by pelzolga123 — APPROVED** [review]
Approved.

**Comment by pelzolga123** [comment]
## Great  work, Congratulation :+1: Project Approved.
You did all changes required previously. Go ahead and merge to master.

As for your question about descriptive branch name, it should reflect changes you are currently doing. For example, this project can have such branch names as: `building-apple-page`, `apple-clone` and so on. It will make more sense in future, when you will have a few milestones in one project.
  
_Goodluck in your next project_ *Happy coding*

**Pull request merged**
